---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbballro/public_html
    - /bin/cp _.sbballroomdance.com.pem.txt $DEPLOYPATH
    - /bin/cp administration.php $DEPLOYPATH
    - /bin/cp archives.php $DEPLOYPATH
    - /bin/cp checkout.html $DEPLOYPATH
    - /bin/cp class.php $DEPLOYPATH
    - /bin/cp classEmail.php $DEPLOYPATH
    - /bin/cp classMem.php $DEPLOYPATH
    - /bin/cp create.php $DEPLOYPATH
    - /bin/cp createNewPassword.php $DEPLOYPATH
    - /bin/cp event.php $DEPLOYPATH
    - /bin/cp eventMem.php $DEPLOYPATH
    - /bin/cp faq.php $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp forgotPassword.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp joinUsNow.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp member.php $DEPLOYPATH
    - /bin/cp processClassItems.php $DEPLOYPATH
    - /bin/cp processClassRegs.php $DEPLOYPATH
    - /bin/cp processEventItems.php $DEPLOYPATH
    - /bin/cp processEventRegs.php $DEPLOYPATH
    - /bin/cp processUserItems.php $DEPLOYPATH
    - /bin/cp regForClasses.php $DEPLOYPATH
    - /bin/cp regForEvents.php $DEPLOYPATH
    - /bin/cp resources.php $DEPLOYPATH
    - /bin/cp secrets.php $DEPLOYPATH
    - /bin/cp signup.php $DEPLOYPATH
    - /bin/cp sponsor.php $DEPLOYPATH
    - /bin/cp yourProfile.php $DEPLOYPATH
    - /bin/cp -R actions $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
