---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbballro/public_html
    - /bin/cp _.sbballroomdance.com.pem.txt $DEPLOYPATH
    - /bin/cp addEventReg.php $DEPLOYPATH
    - /bin/cp administration.php $DEPLOYPATH
    - /bin/cp archives.php $DEPLOYPATH
    - /bin/cp archclass.php $DEPLOYPATH
    - /bin/cp archevent.php $DEPLOYPATH
    - /bin/cp archmember.php $DEPLOYPATH
    - /bin/cp checkout.html $DEPLOYPATH
    - /bin/cp class.php $DEPLOYPATH
    - /bin/cp classEmail.php $DEPLOYPATH
    - /bin/cp classMem.php $DEPLOYPATH
    - /bin/cp create.php $DEPLOYPATH
    - /bin/cp createNewPassword.php $DEPLOYPATH
    - /bin/cp deleteEventReg.php $DEPLOYPATH
    - /bin/cp event.php $DEPLOYPATH
    - /bin/cp eventDesc.php $DEPLOYPATH
    - /bin/cp eventMem.php $DEPLOYPATH
    - /bin/cp faq.php $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp forgotPassword.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp joinonline.php $DEPLOYPATH
    - /bin/cp joincancel.php $DEPLOYPATH
    - /bin/cp joinsuccess.php $DEPLOYPATH
    - /bin/cp joinUsNow.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp member.php $DEPLOYPATH
    - /bin/cp payments.php $DEPLOYPATH
    - /bin/cp processClassItems.php $DEPLOYPATH
    - /bin/cp processClassRegs.php $DEPLOYPATH
    - /bin/cp processEventItems.php $DEPLOYPATH
    - /bin/cp processEventRegs.php $DEPLOYPATH
    - /bin/cp processOptionItems.php $DEPLOYPATH
    - /bin/cp processUserItems.php $DEPLOYPATH
    - /bin/cp profileClasses.php $DEPLOYPATH
    - /bin/cp profileEvents.php $DEPLOYPATH
    - /bin/cp profileMem.php $DEPLOYPATH
    - /bin/cp RegEventBody.php $DEPLOYPATH
    - /bin/cp regForClasses.php $DEPLOYPATH
    - /bin/cp regForEvents.php $DEPLOYPATH
    - /bin/cp regForEventsOnline.php $DEPLOYPATH
    - /bin/cp regcancel.php $DEPLOYPATH
    - /bin/cp regPaycancel.php $DEPLOYPATH
    - /bin/cp regPaysuccess.php $DEPLOYPATH
    - /bin/cp regsuccess.php $DEPLOYPATH
    - /bin/cp regsuccesst.php $DEPLOYPATH
    - /bin/cp renewcancel.php $DEPLOYPATH
    - /bin/cp renewNow.php $DEPLOYPATH
    - /bin/cp renewNowO.php $DEPLOYPATH
    - /bin/cp renewsuccess.php $DEPLOYPATH
    - /bin/cp resources.php $DEPLOYPATH
    - /bin/cp SBDCAAClasses.php $DEPLOYPATH
    - /bin/cp SBDCAAEvents.php $DEPLOYPATH
    - /bin/cp SBDCAAMembers.php $DEPLOYPATH
    - /bin/cp SBDCAAVisitors.php $DEPLOYPATH
    - /bin/cp SBDCAbout.php $DEPLOYPATH
    - /bin/cp SBDCAClasses.php $DEPLOYPATH
    - /bin/cp SBDCAClassest.php $DEPLOYPATH
    - /bin/cp SBDCAEvents.php $DEPLOYPATH
    - /bin/cp SBDCAMembers.php $DEPLOYPATH
    - /bin/cp SBDCAOptions.php $DEPLOYPATH
    - /bin/cp SBDCAVisitors.php $DEPLOYPATH
    - /bin/cp SBDCBoard.php $DEPLOYPATH
    - /bin/cp SBDCClasses.php $DEPLOYPATH
    - /bin/cp SBDCContact.php $DEPLOYPATH
    - /bin/cp SBDCDJInfo.php $DEPLOYPATH
    - /bin/cp SBDCEvents.php $DEPLOYPATH
    - /bin/cp SBDCEventst.php $DEPLOYPATH
    - /bin/cp SBDCHelp.php $DEPLOYPATH
    - /bin/cp SBDCInstructor.php $DEPLOYPATH
    - /bin/cp SBDCMemberDirectory.php $DEPLOYPATH
    - /bin/cp SBDCOtherVol.php $DEPLOYPATH
    - /bin/cp SBDCPictures.php $DEPLOYPATH
    - /bin/cp signup.php $DEPLOYPATH
    - /bin/cp specialevent.php $DEPLOYPATH
    - /bin/cp sponsor.php $DEPLOYPATH
    - /bin/cp updateEventReg.php $DEPLOYPATH
    - /bin/cp yourProfile.php $DEPLOYPATH
    - /bin/cp -R actions $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
