---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbballro/public_html
    -  /bin/cp -R actions $DEPLOYPATH
    -  /bin/cp -R config $DEPLOYPATH
    -  /bin/cp -R css $DEPLOYPATH
    -  /bin/cp -R img $DEPLOYPATH
    -  /bin/cp -R includes $DEPLOYPATH
    -  /bin/cp -R js $DEPLOYPATH
    -  /bin/cp -R models $DEPLOYPATH 
    -  /bin/cp -R footer.php $DEPLOYPATH
    -  /bin/cp -R index.php $DEPLOYPATH
    -  /bin/cp -R login.php $DEPLOYPATH
    -  /bin/cp -R logout.php $DEPLOYPATH
    -  /bin/cp -R yourProfile.php $DEPLOYPATH
    -  /bin/cp -R resources.php $DEPLOYPATH
    -  /bin/cp -R signup.php $DEPLOYPATH
   
    